In [266]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [267]:
df = pd.read_csv("homeprices.csv")

In [268]:
dummies = pd.get_dummies(df.town)

In [269]:
merged_df = pd.concat([df,dummies],axis="columns")
final = merged_df.drop(['town','west windsor'],axis="columns")

In [270]:
model = LinearRegression()

In [271]:
X = final.drop('price',axis="columns")
y = final.price

In [272]:
model.fit(X,y)

LinearRegression()

In [273]:
model.predict([[2800,0,1]])

array([590775.63964739])

In [274]:
model.predict([[3400,0,0]])

array([681241.66845839])

In [275]:
model.score(X,y) # for predict the model score in the end of the session

0.9573929037221873

# Without ColumnTransfer as VIdeo
### codebasics machine learning tutorial

In [276]:
#from sklearn.preprocessing import LabelEncoder

In [277]:
#le = LabelEncoder()

In [278]:
#dfle = df 
#dfle.town = le.fit_transform(dfle.town)

In [279]:
#X = dfle[['town','area']].values
#y = dfle.price

In [280]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
#ct = ColumnTransformer([(dfle[['town','area']].values, OneHotEncoder(), [0])])
#ohe = OneHotEncoder()
#

#print(ct)

In [281]:
#dataset = np.array(ct.fit_transform(X), dtype = np.str)

# From The ColumnTransformer

In [282]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [283]:
ct = ColumnTransformer([('encoder', OneHotEncoder(), [0])], remainder='passthrough')

In [284]:
X = df[['town','area']]
X = np.array(ct.fit_transform(X))
y = df.price

In [285]:
X = X[:,1:]

In [287]:
model.fit(X,y)

LinearRegression()

In [288]:
model.predict([[1,0,2800]])

array([590775.63964739])

In [289]:
model.score(X,y)

0.9573929037221873