## Cross Validation

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

### Logistic Regression(Pipeline)

In [3]:
pipe = make_pipeline(StandardScaler(), LogisticRegression(solver='lbfgs', max_iter=1000))
pipe.fit(X_train,y_train)
pipe.score(X_test,y_test)

0.9777777777777777

### Using SVC model

In [4]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9925925925925926

### Random Forest Classifier

In [5]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9814814814814815

### K Fold Validation

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)*100

In [9]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

97.96296296296296

In [10]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [11]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_lr.append(get_score(make_pipeline(StandardScaler(), LogisticRegression()),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))
    

 ### Cross Val Score

In [12]:
from sklearn.model_selection import cross_val_score

In [16]:
cross_val_score(pipe,digits.data,digits.target).mean()

0.9198916744042093

In [17]:
cross_val_score(SVC(),digits.data,digits.target).mean()

0.9632838130609718

In [21]:
cross_val_score(RandomForestClassifier(n_estimators=80),digits.data,digits.target).mean()

0.9404704425874343